Added Constellation method `to_inst`
pysat/pysat pull request #1075
Opened 2023-01-10 13:31 UTC by aburrell

# Description

Addresses #764 by adding the last of the targeted methods, `to_inst`, to the Constellation.  Supporting methods/functions were added to Instrument and utils.coords.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

Added an example in the tutorial and a unit test.

**Test Configuration**:
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

2023-03-03 18:50 UTC, jklenzing requested changes

2023-03-03 18:50 UTC, jklenzing commented on docs/tutorial/tutorial_constellation.rst
> +	  print(icon)
```suggestion
    import pysat
    import pysatNASA

    # Initalize the ICON Constellation using the ICON module
    icon = pysat.Constellation(cont_module=pysatNASA.constellations.icon)

    # Display the results
    print(icon)
```
tabs are messed up here.  Displays correctly, copy and paste does not work

2023-03-03 18:50 UTC, jklenzing commented on docs/tutorial/tutorial_constellation.rst
> +	  print(rt_inst)
```suggestion
    # Download today's data and load it into the Constellation
    ace_rt.download()
    ace_rt.load(date=ace_rt.today())

    # Convert the output to an Instrument
    rt_inst = ace_rt.to_inst()
    print(rt_inst)
```

2023-03-03 18:50 UTC, jklenzing commented on docs/tutorial/tutorial_constellation.rst
> +	  print(rt_inst)
Getting secret character `^I` when I copy paste into terminal.

2023-03-03 18:50 UTC, jklenzing commented on docs/tutorial/tutorial_constellation.rst
> +This yeilds:
```suggestion
This yields:
```

2023-03-03 18:58 UTC, jklenzing commented
This is a very specific problem that probably doesn't need to be addressed, but I will note that the current invoking of the registry here requires all instruments in the registry to work.  This creates an issue if non-functional branches of other packages are open.

2023-03-03 20:27 UTC, aburrell commented
> This is a very specific problem that probably doesn't need to be addressed, but I will note that the current invoking of the registry here requires all instruments in the registry to work.

Perhaps the best thing for us to do is put a note for developers that recommends they not update their registry until packages are merged in?

2023-03-03 20:37 UTC, jklenzing commented
> > This is a very specific problem that probably doesn't need to be addressed, but I will note that the current invoking of the registry here requires all instruments in the registry to work.
> 
> Perhaps the best thing for us to do is put a note for developers that recommends they not update their registry until packages are merged in? Either way, it's outside the scope of this pull request.

I agree it's out of scope, just noting this because I found it strange.

2023-03-03 20:41 UTC, aburrell commented
> I agree it's out of scope, just noting this because I found it strange.

I guess this reveals how frequently I use the registry 🦦

2023-03-07 23:50 UTC, jklenzing reviewed
Tested with various instruments, looks like it works as expected. Some issues in the docs.

2023-03-07 23:50 UTC, jklenzing commented on docs/tutorial/tutorial_constellation.rst
> +    icon = pysat.Constellation(cont_module=pysatNASA.constellations.icon)
```suggestion
    icon = pysat.Constellation(const_module=pysatNASA.constellations.icon)
```

2023-03-07 23:50 UTC, jklenzing commented on docs/tutorial/tutorial_constellation.rst
> +    icon = pysat.Constellation(cont_module=pysatNASA.constellations.icon)
As currently defined at pysatNASA, the icon constellation will never load.  See https://github.com/pysat/pysatNASA/issues/152

2023-03-08 18:10 UTC, jklenzing approved these changes
:otter:

2023-03-09 12:58 UTC, merged