TST: Clean warnings
pysat/pysat pull request #1129
Opened 2023-07-05 20:29 UTC by aburrell

# Description

Addresses #1009 by adding a general test triggered by an optional testing variable to the standard set of Instrument tests.  Adapted the clean method in the test instruments to run all potential iterations of the allowed behaviour, which includes:

- logging messages
- warnings
- errors
- changing the clean level

Updated the documentation to describe how this testing should be done.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

Added unit tests.  Also added this line to `ace_epam.py` in pysatSpaceWeather and ran the local unit tests.

```
# Set clean warning tests
_clean_warn = {'dusty': ('logger', 'WARN',
                         "unused clean level 'dusty', reverting to 'clean'",
                         'clean')}
```

**Test Configuration**:
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

2023-07-06 14:34 UTC, aburrell commented on docs/new_instrument.rst
> +   _clean_warn = {'dusty': ('logger', 'WARN', "I am a warning!", 'clean')}
```suggestion
   _clean_warn = {inst_id: {tag: {'dusty': ('logger', 'WARN', "I am a warning!", 'clean')} for tag in inst_ids[inst_id]} for inst_id in inst_ids.keys()}
```

2023-07-06 15:46 UTC, aburrell commented on pysat/tests/classes/cls_instrument_library.py
> +                        assert not test_inst.empty
```suggestion
```

These lines can never be reached, since 'none' bypasses the clean method.

2023-07-06 17:26 UTC, aburrell commented on docs/new_instrument.rst
> +                                ('error, ValueError, 'I am an error', 'dusty')]}
```suggestion
                                ('error', ValueError, 'I am an error', 'dusty')]}
```

2023-07-10 18:54 UTC, jklenzing reviewed
Looks good. I would suggest restructuring so that tests where nothing is run are skipped to be consistent with similar tests elsewhere.

2023-07-11 15:09 UTC, aburrell commented
The decrease in coverage is consistent with tests not being skipped and edge cases for ecosystem packages not being triggered.

2023-07-11 15:15 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
> +    """Ensure the strict time flag does not interfere with other tests.
Technically, this loads data in addition to setting the `strict_time_flag`. Tested this code manually, and it does what it should. Modifying `test_inst` in place makes me a little nervous, but it's probably fine as long as the docstring is clear.

2023-07-11 15:19 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
> +            # the cleaning tests
```suggestion
            # Make sure the strict time flag doesn't interfere with
            # the load tests
```

2023-07-11 18:00 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
>              assert target not in test_inst.data
this is the bit that has changed. `set_strict_time_flag` loads the data (which is why 393 passes). But in some cases the new function will force clean to be 'none', which is a change in behaviour.

2023-07-12 17:23 UTC, jklenzing requested changes

2023-07-12 17:23 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
> +def set_strict_time_flag(test_inst, date, raise_error=False, clean_off=True):
```suggestion
def load_and_set_strict_time_flag(test_inst, date, raise_error=False, clean_off=True):
```

2023-07-12 17:23 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
> +    """Ensure the strict time flag does not interfere with other tests.
```suggestion
    """Load data and set the strict time flag if needed for other tests.
```

2023-07-12 17:23 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
> +                set_strict_time_flag(test_inst, date)
```suggestion
                load_and_set_strict_time_flag(test_inst, date)
```

2023-07-12 17:23 UTC, jklenzing commented on pysat/tests/classes/cls_instrument_library.py
```suggestion
            load_and_set_strict_time_flag(test_inst, date, raise_error=True,
                                          clean_off=False)

```

2023-07-13 13:28 UTC, jklenzing approved these changes

2023-07-13 13:31 UTC, merged