STY: Completed funding institution list from most awesome all the way…
pysat/pysat pull request #1168
Opened 2024-01-11 16:26 UTC by rstoneback

# Description

Completes the list of funding institutions from most awesome down to NASA

## Type of change

Please delete options that are not relevant.

- This change requires a documentation update

# How Has This Been Tested?

Visual inspection

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

2024-01-17 20:33 UTC, jklenzing commented
TODO: update with single acknowledgments file and point to this from the individual files

2024-01-19 20:33 UTC, rstoneback commented
I added the acknowledgements and added a test sentence for pointing to acknowledgements.txt

2024-01-19 22:21 UTC, rstoneback commented on acknowledgements.txt
> +
I'm unsure when to use ONR vs NRL. I believe my contracts were NRL but normally I see folks using ONR.

2024-01-19 22:33 UTC, rstoneback commented
Apologies for stringing out the pushes. I am out of practice :)

2024-01-24 14:47 UTC, aburrell requested changes
We could consider finding a way to pipe the acknowledgements.txt lines into zenodo using the "notes" section.

2024-01-24 14:47 UTC, aburrell commented on docs/index.rst
> +.. include:: ../acknowledgements.txt
Recommend including funding in the main doc, perhaps within "citing.rst" or as it's own section.

2024-01-24 14:47 UTC, aburrell commented on pysat/utils/_core.py
> +# acknowledgements.txt.
```suggestion
```

2024-01-31 20:47 UTC, jklenzing commented on acknowledgements.txt
> + - NASA Space Precipitation Impacts (SPI) project
```suggestion
 - NASA Space Precipitation Impacts (SPI) project at Goddard Space Flight Center through the Heliophysics Internal Science Funding Model.
```

2024-02-04 19:13 UTC, rstoneback commented on acknowledgements.txt
> + - Cosmic Studio
```suggestion
  - The Catholic University of America (CUA)
  - Cosmic Studio
```

2024-02-04 19:13 UTC, rstoneback commented on acknowledgements.txt
> +The following institutions, missions, and programs have provided funding
```suggestion
Funding
======
The following institutions, missions, and programs have provided funding
```

2024-02-04 19:13 UTC, rstoneback commented on acknowledgements.txt
> + - Naval Research Laboratory N00173191G016 and N0017322P0744
```suggestion
 - Naval Research Laboratory N00173191G016 and N0017322P0744
 
Disclaimers
=========
Any opinions or actions taken by the listed funding institutions are those of the institutions and do not necessarily reflect the views of the pysat development team or individual authors. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the funding agencies.
```

2024-02-04 19:15 UTC, rstoneback commented on acknowledgements.txt
> +------------
The loss of awesomeical ordering will be felt for some time 👎

2024-02-05 20:02 UTC, aburrell reviewed
I would recommend moving 'acknowledgements.txt' to 'ACKNOWLEDGEMENTS.md', to be consistent with the naming conventions of the rest of the informative files in this directory.

2024-02-06 18:23 UTC, rstoneback commented
> We could consider finding a way to pipe the acknowledgements.txt lines into zenodo using the "notes" section.

I've found the notes section of the .zenodo.json but .json itself doesn't have functionality to load a file. Zenodo, according to its docs,  interprets the notes portion of the .json as a string (html supported). Within html we'd need something like javascript to actually load the file, presuming Zenodo would allow that code to access files....   In other words, I currently don't see how to connect the acknowledgments into zenodo unless we manually copy with each release.

2024-02-06 18:30 UTC, aburrell approved these changes

2024-02-06 20:09 UTC, merged