DEP: use of numeric sat_id to specify number of points
pysat/pysat pull request #736
Opened 2021-03-16 21:45 UTC by jklenzing

# Description

Complements #735.  Moves those warnings here as part of 2.3.0.

I've included notes in the docs throughout the instruments for usage.  Let me know if these should be done differently.

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

testing via travis CI

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

2021-03-17 15:51 UTC, aburrell requested changes

2021-03-17 15:51 UTC, aburrell commented on CHANGELOG.md
> +     - The usage of a numeric string for `sat_id` to specify number of points
Does this need to be in a sublist when there's only one item?

2021-03-17 15:51 UTC, aburrell commented on pysat/instruments/pysat_testing.py
> +    .. deprecated:: 2.3.0
In other deprecations like this, I've added the new kwarg, so they can use either method for this release.  Recommend doing that here, and in the rest of the testing instruments.

2021-03-17 15:51 UTC, aburrell commented on pysat/tests/test_instruments.py
> +        assert war[0].category == DeprecationWarning
Need to also test warning message, to ensure the correct deprecation warning was caught.

2021-03-17 15:52 UTC, aburrell commented on pysat/tests/test_instruments.py
> +        assert war[0].category == DeprecationWarning
Also, I added a deprecation warning evaluation function in instruments.methods.testing that can be used here.

2021-03-18 13:05 UTC, aburrell reviewed
I didn't notice last time, but the deprecation warnings in the doc strings elsewhere have all been placed below the description and above the first section block.

Also, do you think it would be worth changing the use of `sat_id` in the unit tests here?  That had been part of my plan originally, since it would make the log smaller.

2021-03-18 13:05 UTC, aburrell commented on pysat/instruments/methods/testing.py
> +      will be replaced by the `num` keyword as an integer)
Move this up above the parameters block

2021-03-18 15:10 UTC, jklenzing commented
> Also, do you think it would be worth changing the use of `sat_id` in the unit tests here? That had been part of my plan originally, since it would make the log smaller.

This is a good idea.  They should be all changed in the latest push.  🤞

2021-03-18 16:15 UTC, aburrell approved these changes
Looks great!

2021-03-18 16:35 UTC, merged